site_name: Oudiamora

theme:
  name: material
  logo: images/logo.jpg
  language: fr # Langue par défaut de l'interface

plugins:
  - search # Conserve la barre de recherche
  - i18n:
      default_language: fr
      languages:
        fr: 
          name: Français
          build: true
        en: 
          name: English
          build: true

nav:
  - Accueil: index.md
  - Les Concepts Clés (Lexique): definitions.md
  - La Puissance de la Synergie: combinaison-puissance.md
  - OSC Pilotes:
      - Membres: membres.md
      - Devenir membre: devenir-membre.md
  - Boîte à Prompts: boite-a-outils.md
