site_name: Oudiamora, la puissance de l'IA & Open Data au service des communautés 
site_description: Accompagner l'inclusion sociale par le numérique local.

theme:
  name: material
  logo: images/logo.jpg
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mode clair
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

plugins:
  - search
  - blog:
      blog_dir: blog
      post_readtime: true

nav:
  - Accueil: index.md
  - La Puissance de la Synergie Open data + IA: combinaison-puissance.md
  - Les Concepts Clés (Lexique): definitions.md
  - OSC Pilotes:
      - Membres: membres.md
      - Devenir membre: devenir-membre.md
  - Ressources:
      - Ressources Open Data: ressources-open-data.md
      - IA Génératives: ia-generatives.md
      - Cas d'usage: cas-usages.md
  - sur notre agenda: evenements.md
  - Actualités / Blog: blog/index.md
  - Contact: contact.md
